### ISSUE TITLE
Wallpaper thats in the hyprland hall of fame where?

### ISSUE THREAD

**Issue by Virayen** [lauroro/dots#2]
Hello! 
I saw this wallpaper you have, and really like it
![image](https://github.com/user-attachments/assets/e9badd91-702a-4d82-940b-4f86c6134cd3)
I was wondering where I could get it, since I cant find it in here, 
Id also like to know what script your running on the right, that shows the system info, 

Thanks!

**Comment by lauroro** [comment]
Hey, I'm sorry but there was a mistake back then. I think vaxry or his staff confused my rice with Lyasm's. Well, mine was Lyasm's, so I really can't help you. Never borhered to make them fix it cause I stopped interacting with hyprland community since a while.

-------- Messaggio originale --------
18/08/24 07:25, Zenith  ha scritto:

**Comment by Virayen** [comment]
Oh alright, could you link me to the original dots then?

**Comment by lauroro** [comment]
I have no idea, you should try to look into their dots repo history. I'm sorry.

-------- Messaggio originale --------
18/08/24 20:24, Zenith  ha scritto:

**Comment by Virayen** [comment]
Oh thats alright, have a great day or night!
